### ISSUE TITLE
Incompatible with Python 3.11

### ISSUE THREAD

**Issue by wilco375** [Infinidat/infi.devicemanager#14]
The library does not seem to work with Python 3.11. It does work on Python 3.10 for me. `getargspec` seems to be a deprecated function that was removed in Python 3.11
```
>>> from infi.devicemanager import DeviceManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Wilco van Beijnum\AppData\Local\Programs\Python\Python311\Lib\site-packages\infi\devicemanager\__init__.py", line 5, in <module>
    from .setupapi import functions, properties, constants
  File "C:\Users\Wilco van Beijnum\AppData\Local\Programs\Python\Python311\Lib\site-packages\infi\devicemanager\setupapi\functions.py", line 3, in <module>
    from infi.pyutils.decorators import wraps
  File "C:\Users\Wilco van Beijnum\AppData\Local\Programs\Python\Python311\Lib\site-packages\infi\pyutils\decorators.py", line 28, in <module>
    monkey_patch(inspect, "getargspec", inspect_getargspec_patch)
  File "C:\Users\Wilco van Beijnum\AppData\Local\Programs\Python\Python311\Lib\site-packages\infi\pyutils\patch.py", line 7, in monkey_patch
    setattr(module, original_name, getattr(module, name))
                                   ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?```

**Comment by tanmayyb** [comment]
same issue

**Comment by afantima2024** [comment]
Same issue here.

![Image](https://github.com/user-attachments/assets/67a11ea7-3c1d-4869-9946-eb5338c5c115)
